// Product type definition
export type Product = {
  id: number;
  name: string;
  price: number;
  description: string;
  features: string[];
  sizes: string[];
  colors: string[];
  category: string;
  image: string;
};

// Products data
export const products: Record<string, Product> = {
  "1": {
    id: 1,
    name: "Basic T-Shirt",
    price: 19.99,
    description: "A comfortable and stylish basic t-shirt made from 100% cotton.",
    features: ["100% cotton", "Regular fit", "Machine washable", "Available in multiple colors"],
    sizes: ["XS", "S", "M", "L", "XL"],
    colors: ["Black", "White", "Navy", "Gray"],
    category: "Clothing",
    image: "/placeholder.svg?height=400&width=300&text=Basic+T-Shirt",
  },
  "2": {
    id: 2,
    name: "Denim Jeans",
    price: 49.99,
    description: "Classic denim jeans with a comfortable stretch fit.",
    features: ["98% cotton, 2% elastane", "Regular fit", "Machine washable", "Five pocket design"],
    sizes: ["28", "30", "32", "34", "36"],
    colors: ["Blue", "Black", "Gray"],
    category: "Clothing",
    image: "/placeholder.svg?height=400&width=300&text=Denim+Jeans",
  },
  "3": {
    id: 3,
    name: "Sneakers",
    price: 79.99,
    description: "Comfortable everyday sneakers with cushioned insoles.",
    features: ["Synthetic upper", "Rubber outsole", "Cushioned insole", "Lace-up closure"],
    sizes: ["7", "8", "9", "10", "11", "12"],
    colors: ["White", "Black", "Gray", "Red"],
    category: "Footwear",
    image: "/placeholder.svg?height=400&width=300&text=Sneakers",
  },
  "4": {
    id: 4,
    name: "Backpack",
    price: 39.99,
    description: "Durable backpack with multiple compartments for everyday use.",
    features: ["Water-resistant material", "Padded laptop sleeve", "Multiple pockets", "Adjustable straps"],
    sizes: ["One Size"],
    colors: ["Black", "Navy", "Gray", "Green"],
    category: "Accessories",
    image: "/placeholder.svg?height=400&width=300&text=Backpack",
  },
  "5": {
    id: 5,
    name: "Wireless Headphones",
    price: 129.99,
    description: "Premium wireless headphones with noise cancellation.",
    features: ["Active noise cancellation", "30-hour battery life", "Bluetooth 5.0", "Built-in mic"],
    sizes: ["One Size"],
    colors: ["Black", "White", "Blue"],
    category: "Electronics",
    image: "/placeholder.svg?height=400&width=300&text=Headphones",
  },
  "6": {
    id: 6,
    name: "Smart Watch",
    price: 199.99,
    description: "Fitness tracker and smartwatch with heart rate monitor.",
    features: ["Heart rate monitor", "Water resistant", "7-day battery", "Touch screen"],
    sizes: ["Small", "Medium", "Large"],
    colors: ["Black", "Silver", "Rose Gold"],
    category: "Electronics",
    image: "/placeholder.svg?height=400&width=300&text=Smart+Watch",
  },
  "7": {
    id: 7,
    name: "Leather Wallet",
    price: 34.99,
    description: "Genuine leather wallet with multiple card slots.",
    features: ["Genuine leather", "6 card slots", "ID window", "RFID blocking"],
    sizes: ["One Size"],
    colors: ["Brown", "Black", "Tan"],
    category: "Accessories",
    image: "/placeholder.svg?height=400&width=300&text=Leather+Wallet",
  },
  "8": {
    id: 8,
    name: "Dress Shirt",
    price: 44.99,
    description: "Formal dress shirt with slim fit design.",
    features: ["100% cotton", "Slim fit", "Button-down collar", "Machine washable"],
    sizes: ["S", "M", "L", "XL"],
    colors: ["White", "Blue", "Pink", "Gray"],
    category: "Clothing",
    image: "/placeholder.svg?height=400&width=300&text=Dress+Shirt",
  },
  "9": {
    id: 9,
    name: "Running Shoes",
    price: 89.99,
    description: "Lightweight running shoes with responsive cushioning.",
    features: ["Breathable mesh", "Shock absorption", "Non-slip sole", "Removable insole"],
    sizes: ["7", "8", "9", "10", "11", "12"],
    colors: ["Black/Red", "White/Blue", "Gray/Orange"],
    category: "Footwear",
    image: "/placeholder.svg?height=400&width=300&text=Running+Shoes",
  },
  "10": {
    id: 10,
    name: "Sunglasses",
    price: 59.99,
    description: "UV protection sunglasses with polarized lenses.",
    features: ["100% UV protection", "Polarized lenses", "Lightweight frame", "Case included"],
    sizes: ["One Size"],
    colors: ["Black", "Tortoise", "Silver", "Gold"],
    category: "Accessories",
    image: "/placeholder.svg?height=400&width=300&text=Sunglasses",
  },
  "11": {
    id: 11,
    name: "Hoodie",
    price: 39.99,
    description: "Warm and comfortable hoodie for casual wear.",
    features: ["80% cotton, 20% polyester", "Kangaroo pocket", "Adjustable drawstring", "Machine washable"],
    sizes: ["S", "M", "L", "XL", "XXL"],
    colors: ["Black", "Gray", "Navy", "Red"],
    category: "Clothing",
    image: "/placeholder.svg?height=400&width=300&text=Hoodie",
  },
  "12": {
    id: 12,
    name: "Bluetooth Speaker",
    price: 79.99,
    description: "Portable Bluetooth speaker with 20-hour battery.",
    features: ["IPX7 waterproof", "20hr playtime", "Stereo sound", "Built-in mic"],
    sizes: ["One Size"],
    colors: ["Black", "Blue", "Red"],
    category: "Electronics",
    image: "/placeholder.svg?height=400&width=300&text=Speaker",
  },
  "13": {
    id: 13,
    name: "Dress Pants",
    price: 54.99,
    description: "Professional dress pants with wrinkle-resistant fabric.",
    features: ["Wrinkle-resistant", "Stretch fabric", "Flat front", "Machine washable"],
    sizes: ["30", "32", "34", "36", "38"],
    colors: ["Black", "Charcoal", "Navy"],
    category: "Clothing",
    image: "/placeholder.svg?height=400&width=300&text=Dress+Pants",
  },
  "14": {
    id: 14,
    name: "Winter Jacket",
    price: 129.99,
    description: "Insulated winter jacket for cold weather.",
    features: ["Water-resistant", "Thermal insulation", "Adjustable hood", "Multiple pockets"],
    sizes: ["S", "M", "L", "XL"],
    colors: ["Black", "Navy", "Green"],
    category: "Clothing",
    image: "/placeholder.svg?height=400&width=300&text=Winter+Jacket",
  },
  "15": {
    id: 15,
    name: "Smartphone",
    price: 699.99,
    description: "Latest smartphone with high-resolution camera.",
    features: ["6.5\" display", "128GB storage", "Triple camera", "5G capable"],
    sizes: ["One Size"],
    colors: ["Black", "White", "Blue"],
    category: "Electronics",
    image: "/placeholder.svg?height=400&width=300&text=Smartphone",
  },
  "16": {
    id: 16,
    name: "Yoga Mat",
    price: 29.99,
    description: "Non-slip yoga mat for fitness and meditation.",
    features: ["Non-slip surface", "6mm thickness", "Lightweight", "Carry strap included"],
    sizes: ["One Size"],
    colors: ["Purple", "Blue", "Green", "Pink"],
    category: "Fitness",
    image: "/placeholder.svg?height=400&width=300&text=Yoga+Mat",
  },
  "17": {
    id: 17,
    name: "Leather Belt",
    price: 24.99,
    description: "Genuine leather belt with durable buckle.",
    features: ["100% genuine leather", "Brushed nickel buckle", "Adjustable sizing", "Classic design"],
    sizes: ["S", "M", "L", "XL"],
    colors: ["Brown", "Black", "Tan"],
    category: "Accessories",
    image: "/placeholder.svg?height=400&width=300&text=Leather+Belt",
  },
  "18": {
    id: 18,
    name: "Coffee Mug",
    price: 12.99,
    description: "Ceramic coffee mug with ergonomic handle.",
    features: ["15oz capacity", "Dishwasher safe", "Microwave safe", "Splash-resistant lid"],
    sizes: ["One Size"],
    colors: ["White", "Black", "Blue"],
    category: "Home",
    image: "/placeholder.svg?height=400&width=300&text=Coffee+Mug",
  },
  "19": {
    id: 19,
    name: "Dumbbell Set",
    price: 89.99,
    description: "Adjustable dumbbell set for home workouts.",
    features: ["5-25lbs adjustable", "Non-slip grip", "Compact design", "Includes storage rack"],
    sizes: ["One Size"],
    colors: ["Black", "Silver"],
    category: "Fitness",
    image: "/placeholder.svg?height=400&width=300&text=Dumbbell+Set",
  },
  "20": {
    id: 20,
    name: "Desk Lamp",
    price: 34.99,
    description: "LED desk lamp with adjustable brightness.",
    features: ["3 brightness levels", "Adjustable arm", "USB charging port", "Energy efficient"],
    sizes: ["One Size"],
    colors: ["White", "Black", "Silver"],
    category: "Home",
    image: "/placeholder.svg?height=400&width=300&text=Desk+Lamp",
  },
  "21": {
    id: 21,
    name: "Baseball Cap",
    price: 19.99,
    description: "Classic baseball cap with adjustable strap.",
    features: ["100% cotton", "Adjustable strap", "Pre-curved visor", "Machine washable"],
    sizes: ["One Size"],
    colors: ["Black", "Navy", "Red", "Gray"],
    category: "Accessories",
    image: "/placeholder.svg?height=400&width=300&text=Baseball+Cap",
  },
  "22": {
    id: 22,
    name: "Laptop Backpack",
    price: 49.99,
    description: "Professional laptop backpack with USB charging port.",
    features: ["Fits 15\" laptop", "USB charging port", "Anti-theft design", "Water-resistant"],
    sizes: ["One Size"],
    colors: ["Black", "Gray", "Blue"],
    category: "Accessories",
    image: "/placeholder.svg?height=400&width=300&text=Laptop+Backpack",
  },
  "23": {
    id: 23,
    name: "Wireless Mouse",
    price: 29.99,
    description: "Ergonomic wireless mouse with silent click.",
    features: ["2.4GHz wireless", "12-month battery", "Silent click", "Adjustable DPI"],
    sizes: ["One Size"],
    colors: ["Black", "White", "Gray"],
    category: "Electronics",
    image: "/placeholder.svg?height=400&width=300&text=Wireless+Mouse",
  },
  "24": {
    id: 24,
    name: "Water Bottle",
    price: 14.99,
    description: "Insulated stainless steel water bottle.",
    features: ["24oz capacity", "Double-wall insulation", "Leak-proof", "BPA-free"],
    sizes: ["One Size"],
    colors: ["Silver", "Black", "Blue", "Pink"],
    category: "Fitness",
    image: "/placeholder.svg?height=400&width=300&text=Water+Bottle",
  },
  "25": {
    id: 25,
    name: "Polo Shirt",
    price: 29.99,
    description: "Classic polo shirt with moisture-wicking fabric.",
    features: ["Moisture-wicking", "UV protection", "3-button placket", "Machine washable"],
    sizes: ["S", "M", "L", "XL"],
    colors: ["Black", "White", "Navy", "Red"],
    category: "Clothing",
    image: "/placeholder.svg?height=400&width=300&text=Polo+Shirt",
  }
};

// Helper functions
export function getProductById(id: string): Product | undefined {
  return products[id];
}

export function getAllProducts(): Product[] {
  return Object.values(products);
}

export function getProductsByCategory(category: string): Product[] {
  return getAllProducts().filter((product) => product.category === category);
}

export function getFeaturedProducts(count = 4): Product[] {
  return getAllProducts().slice(0, count);
}
